{
  "zero_optimization": {
    "stage": 1,
    "offload_param": {
        "device": "none"
    },
    "offload_optimizer": {
        "device": "none"
    },
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": false,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true
  },
  "fp16": {
     "fp16": true,
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "hysteresis": 2,
     "min_loss_scale": 1
   },
  "comms_logger": {
  "enabled": false,
  "verbose": false,
  "prof_all": false,
  "debug": false
  }

}

