seed_everything: 42

# ---------------------------- TRAINER -------------------------------------------
trainer:
  default_root_dir: ${oc.env:OUTPUT_DIR,exps/sqg}

  precision: 16

  # gpus: null
  num_nodes: null
  accelerator: gpu
  strategy: ddp

  min_epochs: 10
  max_epochs: 100
  enable_progress_bar: true

  sync_batchnorm: True
  enable_checkpointing: True
  # resume_from_checkpoint: null

  # debugging
  fast_dev_run: false

  logger:
    class_path: pytorch_lightning.loggers.tensorboard.TensorBoardLogger #pytorch_lightning.loggers.CSVLogger #pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: ${trainer.default_root_dir}/logs
      name: null
      version: null
      #flush_logs_every_n_steps: 10
      log_graph: False
      default_hp_metric: True
      prefix: ""

  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"

    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: "${trainer.default_root_dir}/checkpoints"
        monitor: "train/loss" #"val/w_rmse" # name of the logged metric which determines when model is improving
        mode: "min" # "max" means higher metric value is better, can be also "min"
        save_top_k: 1 # save k best models (determined by above metric)
        save_last: True # additionaly always save model from last epoch
        verbose: False
        filename: "epoch_{epoch:03d}"
        auto_insert_metric_name: False

    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: "train/loss" # name of the logged metric which determines when model is improving
        mode: "min" # "max" means higher metric value is better, can be also "min"
        patience: 5 # how many validation epochs of not improving until training stops
        min_delta: 0. # minimum change in the monitored metric needed to qualify as an improvement

    # - class_path: pytorch_lightning.callbacks.RichModelSummary
    #   init_args:
    #     max_depth: -1

    # - class_path: pytorch_lightning.callbacks.RichProgressBar

# ---------------------------- MODEL -------------------------------------------
model:
  lr: 5e-4
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 1e-5
  warmup_epochs: 10 
  max_epochs: 100
  warmup_start_lr: 1e-8
  eta_min: 1e-8
  pretrained_path: ""

  net:
    class_path: sqg.model.arch.SQG_ViT
    init_args:
      default_vars: [
          "sqg_0",
          "sqg_10000",
        ]
      img_size: [128, 128]
      patch_size: 4
      embed_dim: 2048
      depth: 24
      decoder_depth: 2
      num_heads: 16
      mlp_ratio: 4
      drop_path: 0.1
      drop_rate: 0.1

# ---------------------------- DATA -------------------------------------------
data:
  root_dir: ../sqg_npy/128
  variables: [
          "sqg_0",
          "sqg_10000",
    ]

  out_variables: ["sqg_0", "sqg_10000"]
  predict_range: 1
  hrs_each_step: 1
  buffer_size: 10000
  batch_size: 4
  num_workers: 1 
  pin_memory: True 

